import UserProvider from "@/components/UserProvider";
import type { Metadata } from "next";
import Theme from "@/components/Theme";
import AuthRequired from "@/components/AuthRequired";
import Navbar from "@/components/Navbar";
import { Box } from "@mui/joy";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Theme>
            <AuthRequired>
              <Navbar />
              <Box p={2} maxWidth="1000px" mx="auto">
                {children}
              </Box>
            </AuthRequired>
          </Theme>
        </body>
      </UserProvider>
    </html>
  );
}
